### ISSUE TITLE
user creation on signup

### ISSUE THREAD

**Issue by muhammad-ammar** [relekang/django-nopassword#57]
@relekang Do i need to create the users separately? Currently it raises `DoesNotExist` [here](https://github.com/relekang/django-nopassword/blob/master/nopassword/backends/base.py#L15). I am just visiting the `/accounts/login/` and it is presenting me a input field with submit button. Upon entering the username in the field i get exception as mentioned above.

**Comment by relekang** [comment]
That is correct. There has to be an existing user for the authentication to work. You would need to create a signup view. You can use the code generation in the signup view and ask for the users email and then create a user and call authenticate. nopassword will then send a login code if there is no keyword argument `code`.

Example
```python
from django.contrib.auth import authenticate

def signup(request):
    # create user as new_user
    authenticate(username=new_user.username)
    return redirect('login')
```

I'm going to close this issue, but please don't hesitate to ask more questions.

**Comment by muhammad-ammar** [comment]
@relekang Bundle of thanks for your reply and code example.
