### ISSUE TITLE
django-nopassword-2.1.0 PIP package installing files outside of nopassword directory

### ISSUE THREAD

**Issue by rsp2k** [relekang/django-nopassword#61]
It appears the pip package is leaking files into the tests modules directory, I think they should be nopassword/tests? Please see the snipped output below from "pip uninstall django-nopassword":

Uninstalling django-nopassword-2.1.0
[SNIP]
**This file was in the right place**
  /home/rpm/python/lib/python2.7/site-packages/nopassword/views.py

**The ones below are suspect:**
  /home/rpm/python/lib/python2.7/site-packages/tests/__init__.py
  /home/rpm/python/lib/python2.7/site-packages/tests/models.py
  /home/rpm/python/lib/python2.7/site-packages/tests/settings.py
  /home/rpm/python/lib/python2.7/site-packages/tests/test_backends.py
  /home/rpm/python/lib/python2.7/site-packages/tests/test_models.py
  /home/rpm/python/lib/python2.7/site-packages/tests/test_views.py
  /home/rpm/python/lib/python2.7/site-packages/tests/tests.py
  /home/rpm/python/lib/python2.7/site-packages/tests/urls.py

**Comment by relekang** [comment]
Thanks a lot for filing this issue! This sounds weird, I'll look into it. The tests should not be installed at all.

**Comment by relekang** [comment]
2.1.1 addresses this. Thanks for reporting.
