### ISSUE TITLE
tag new release supporting Django 2.0+?

### ISSUE THREAD

**Issue by bennettrogers** [relekang/django-nopassword#83]
It looks like Django 2.0 support was added in the last 6 months, but there hasn't been a new release that includes these changes. Would it be possible to release a new version to pypi with these updates?

Thank you for building a package that helps get rid of passwords!

**Comment by AlexInntekt** [comment]
Does the package have any support for Django 2?

The last release 3.0.2 is not compatible with django 2.

I would like to contribute.
@relekang 
Thank you

**Comment by AlexInntekt** [comment]
Does the package have any support for Django 2?
The last release 3.0.2 is not compatible with django 2.
I would like to contribute.
@relekang
Thank you

**Comment by relekang** [comment]
I guess we can just do a release. I might be able to do that tomorrow.

**Comment by relekang** [comment]
I released v4.0.0 now
