### ISSUE TITLE
Some directories are not included when installing with pip

### ISSUE THREAD

**Issue by AlexInntekt** [relekang/django-nopassword#84]
On the left you can see the directories tree from the github. On the right is my lib directory with the package after the installation. Two directories don't exist on my side. "Rest" is the one that I need and is not here. I did install _djangorestframework_ but the problem persists.
<img width="697" alt="restmissing" src="https://user-images.githubusercontent.com/26348552/51438194-86ed5280-1cb1-11e9-9353-17080f1d7cf0.png">

When I clone/download and use the package as an app it works. But using `pip install django-nopassword` fails in installing all directories.

Any suggestion? Is it a bug from your side or it was just me that does something wrong? I over checked this several times and I am clueless. I spotted a similar issue (#6) with templates: https://github.com/relekang/django-nopassword/issues/6

Thank you

**Comment by relekang** [comment]
You should look at the [latest release](https://github.com/relekang/django-nopassword/tree/v3.0.2)

**Comment by AlexInntekt** [comment]
Tusen takk ❤
